"""Add instructor_id to Homework model

Revision ID: 313dc96fe6c4
Revises: 623c27cbd008
Create Date: 2024-11-20 20:52:05.893164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '313dc96fe6c4'
down_revision = '623c27cbd008'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('homework', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instructor_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'student', ['instructor_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('homework', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('instructor_id')

    # ### end Alembic commands ###
